export type TransactionStatus = 'paid' | 'pending';
export type TransactionType = 'income' | 'expense';

export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  category: string;
  subcategory?: string;
  date: string; // ISO string
  status: TransactionStatus;
  description: string;
  isRecurring?: boolean; // True if generated by a recurring bill
  recurringBillId?: string;
}

export interface RecurringBill {
  id: string;
  name: string;
  amount: number;
  category: string;
  dueDay: number; // 1-31
  type: TransactionType;
  status: 'active' | 'paused';
  startDate?: string; // ISO String to know when this bill started
  endDate?: string;
}

export interface Budget {
  id: string;
  categoryId: string;
  subcategory?: string; // Optional subcategory for the budget
  plannedAmount: number;
  month: string; // YYYY-MM
}

export interface Investment {
  id: string;
  name: string;
  type: string; // 'Reserva de Emergência', 'Viagem', 'Casa', 'Celular', 'Outros', etc.
  amount: number;
  goalAmount?: number; // Valor alvo da caixinha
  withdrawnAmount?: number; // Valor Retirado do Patrimônio
  date: string; // ISO string
  icon?: string;
}

export interface Category {
  id: string;
  name: string;
  type: TransactionType;
  color: string;
  icon: string;
  subcategories?: string[];
}

// Example Categories
export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'cat_housing', name: 'Moradia', type: 'expense', color: '#f43f5e', icon: 'home', subcategories: ['Aluguel', 'Condomínio', 'Manutenção'] },
  { id: 'cat_food', name: 'Alimentação', type: 'expense', color: '#f59e0b', icon: 'utensils', subcategories: ['Mercado', 'Restaurante', 'Delivery', 'Padaria'] },
  { id: 'cat_transport', name: 'Transporte', type: 'expense', color: '#3b82f6', icon: 'car', subcategories: ['Combustível', 'Aplicativo', 'Transporte Público', 'Estacionamento', 'IPVA/Manutenção'] },
  { id: 'cat_utilities', name: 'Contas Residenciais', type: 'expense', color: '#8b5cf6', icon: 'zap', subcategories: ['Água', 'Luz', 'Internet', 'Gás', 'Telefone'] },
  { id: 'cat_entertainment', name: 'Lazer', type: 'expense', color: '#ec4899', icon: 'film', subcategories: ['Cinema', 'Shows', 'Jogos', 'Assinaturas'] },
  { id: 'cat_debts', name: 'Dívidas & Crédito', type: 'expense', color: '#ef4444', icon: 'credit-card', subcategories: ['Cartão de Crédito', 'Empréstimo', 'Financiamento', 'Parcelamento'] },
  { id: 'cat_investment', name: 'Investimento', type: 'expense', color: '#6366f1', icon: 'trending-up', subcategories: ['Renda Fixa', 'Renda Variável', 'Cripto', 'Fundos'] },
  { id: 'cat_income_salary', name: 'Salário', type: 'income', color: '#22c55e', icon: 'briefcase', subcategories: ['Fixo', 'Bônus', 'Hora Extra'] },
  { id: 'cat_income_other', name: 'Outras Receitas', type: 'income', color: '#10b981', icon: 'dollar-sign', subcategories: ['Vendas', 'Rendimentos', 'Cashback', 'Presentes'] },
];
